### ISSUE TITLE
Problem: there are no docs

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/mets-reader-writer#30] opened 2017-10-19 00:22 UTC
We should use the `docs/` project already available and we should wire it with Travis CI so it builds the page and pushes it into the gh-pages branch or readthedocs or similar.

**Comment by sevein** [comment] 2017-10-19 00:25
We should also make sure that the PyPI homepage of the project shows useful information, e.g. https://pypi.python.org/pypi/Flask.

**Comment by ablwr** [comment] 2018-12-18 00:58
:anguished:

**Comment by ross-spencer** [comment] 2019-04-09 06:04
Closing as duplicate of https://github.com/archivematica/Issues/issues/609

**Closed by ross-spencer** 2019-04-09 06:04 UTC
